### ISSUE TITLE
Implement the MLD

### ISSUE THREAD

**Issue by naikibro** [naikibro/BatailleNavale#14]
# Implement the MLD
- create the classes from the MLD from the card #10 
- implement the logic between the classes

## Paradigms to implement
- @Override the equals method in one class to compare two objects of the same class
- Encapsulation

![Image](https://github.com/naikibro/BatailleNavale/assets/64978347/29e9fd9d-6a6f-4348-b68d-b16d1587081d)

**Comment by naikibro** [comment]
il me semble que pour les Ships il voulait qu'on fasse hériter chaque type de Ship depuis la classe Ship
Le nom de la classe représenterait alors le type du Ship

**Comment by naikibro** [comment]
bro @tteuru09 j'implémente les classes Map et Tile en même temps que je fais ma carte #16

**Comment by naikibro** [comment]
# Ships

- Carrier (6)
- BattleShip (5)
- Cruiser (4)
- Submarine (3)
- Destroyer (3)

**Comment by tteuru09** [comment]
Ok c'est noté pour le Map et Tile. Tfaçon j'avais pas hoa touché.

**Comment by tteuru09** [comment]
Je viens de créer la première version de la classe " Ship " et de ses sous-classes. J'ai fait un pull request bro @naikibro
