### ISSUE TITLE
create the game phases

### ISSUE THREAD

**Issue by naikibro** [naikibro/BatailleNavale#20]
# Represent all the game phases

- create the global variables to handle the Gameplay logic
- implement the `Player` class
- implement the `GamePhases` class
- implement the `Game` class

**Comment by naikibro** [comment]
hello @tteuru09 , i have a question 

how do we define that a user has won the party ?

is it when the sum of all the ships hits ( incremented everytime a ship is shot ) is equal to a certain fixed number ?

    - exemple : when i have 25 confirmed hits, i can say that i have won the party

**Comment by naikibro** [comment]
hello @tteuru09 for this card i will implement the `Player` class and a `Fleet` class to instanciate the start of a party

i will also create the different pages of the gameplay:
- LandingPage : the first page where we initialize the party
- WarfieldPage : where the game happens
- GameOverPage : where show the scores and a prompt to play again

**Comment by tteuru09** [comment]
Hello @naikibro,

I think you had a great idea about how to define when the player win the game.
Let's try to implement that.
